### ISSUE TITLE
Defaults not preserved

### ISSUE THREAD

**Issue by lazy-pete** [stevebuk1/pv_opt#146]
**Describe the bug**

I fairly regularly find that my PV-opt setup ‘loses’ its default settings. I have edited the pv_opt.py to have read only as false etc so a HA / Appdaemon restart doesn’t turn things off, however this doesn’t seem to work. I’m trying to get the logs, however I must’ve set that up wrong as there nothing in my Share/logs folder. 

Meantime a screenshot to illustrate what I found this morning (same as often happens) in case I’ve just edited the file incorrectly. 

**To Reproduce**

**Expected behavior**

**Screenshots**

![IMG_5992](https://github.com/fboundy/pv_opt/assets/30950467/d8d51e88-2187-4ffa-95b9-7bacf8a119d6)
![IMG_5991](https://github.com/fboundy/pv_opt/assets/30950467/7ee32df1-0959-4d10-a48a-171077bf5145)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mergwyn** [comment]
I also set `readonly` to `false` but rather than modify `pv_opt.py` I change the config file `config.yaml` eg.
```
pv_opt:
  module: pv_opt
  class: PVOpt
  dependencies:
    - pvpy
    - solis

  log: pv_opt_log
  prefix: pvopt
  #debug: True


# User configuration ---  EDIT AWAY! ---

  inverter_type: "SOLIS_SOLAX_MODBUS"
  # inverter_type: "SOLIS_CORE_MODBUS"
  # inverter_type: SOLIS_SOLARMAN
  device_name: solax

  # If true the current config in HA will be over-written with that in the config.yaml.
  overwrite_ha_on_restart: true
  redact_personal_data_from_log: true

  forced_charge: true
  forced_discharge: true
  allow_cyclic: false
  read_only: false
```
This works well for me - it might be worth trying this method.

**Comment by fboundy** [comment]
The setting to change is overwite_ha_on_restart. Set this to false and settings in config.yaml will be ignored in favour of whatever you have set in HA

**Comment by lazy-pete** [comment]
Thanks both - I’ll try one / other / both of those suggestions.

Cheers,

Pete

**Comment by lazy-pete** [comment]
Hi - I tried both those options, but still not holding my custom defaults. 

2024-03-12 20:50:00.306604 INFO AppDaemon: Loading app pv_opt using class PVOpt from module pv_opt
2024-03-12 20:50:00.307206 ERROR pv_opt: User defined log pv_opt_log not found
2024-03-12 20:50:00.307738 INFO AppDaemon: Calling initialize() for pv_opt
2024-03-12 20:50:00.308301 INFO pv_opt: 
2024-03-12 20:50:00.308742 INFO pv_opt: ******************* PV Opt v3.9.5 *******************
2024-03-12 20:50:00.309369 INFO pv_opt: 
2024-03-12 20:50:00.309564 ERROR pv_opt: User defined log pv_opt_log not found
2024-03-12 20:50:00.309947 ERROR pv_opt: User defined log pv_opt_log not found
2024-03-12 20:50:00.310527 INFO pv_opt: Local timezone set to GB
2024-03-12 20:50:00.311220 INFO pv_opt: Time Zone Offset: 0.0 minutes
2024-03-12 20:50:00.311877 INFO pv_opt: Inverter type: SOLIS_SOLAX_MODBUS: inverter module: solis.py
2024-03-12 20:50:00.312401 WARNING pv_opt: pv_opt: Entity sensor.pvopt_status not found in namespace default
2024-03-12 20:50:00.312783 INFO AppDaemon: pv_opt: Entity sensor.pvopt_status created in namespace: default
2024-03-12 20:50:00.363916 INFO pv_opt: Reading arguments from YAML:
2024-03-12 20:50:00.364584 INFO pv_opt: -----------------------------------
2024-03-12 20:50:00.365577 INFO pv_opt:     consumption_history_days           = 7                                                              7: value in YAML
2024-03-12 20:50:00.366792 INFO pv_opt:     forced_charge                      = True                                                        True: value in YAML
2024-03-12 20:50:00.367785 INFO pv_opt:     forced_discharge                   = False                                                      False: value in YAML
2024-03-12 20:50:00.368730 INFO pv_opt:     allow_cyclic                       = False                                                      False: value in YAML
2024-03-12 20:50:00.369684 INFO pv_opt:     read_only                          = False                                                      False: value in YAML
2024-03-12 20:50:00.370598 INFO pv_opt:     battery_capacity_wh                = 10000                                                      10000: value in YAML
2024-03-12 20:50:00.371575 INFO pv_opt:     inverter_efficiency_percent        = 97                                                            97: value in YAML
2024-03-12 20:50:00.372476 INFO pv_opt:     charger_efficiency_percent         = 91                                                            91: value in YAML
2024-03-12 20:50:00.373353 INFO pv_opt:     charger_power_watts                = 3500                                                        3500: value in YAML
2024-03-12 20:50:00.374248 INFO pv_opt:     inverter_power_watts               = 3600                                                        3600: value in YAML
2024-03-12 20:50:00.375121 INFO pv_opt:     inverter_loss_watts                = 100                                                          100: value in YAML
2024-03-12 20:50:00.376665 INFO pv_opt:     id_solcast_today                   = sensor.solcast_pv_forecast_forecast_today                 4.0415: value(s) in YAML
2024-03-12 20:50:00.377988 INFO pv_opt:     id_solcast_tomorrow                = sensor.solcast_pv_forecast_forecast_tomorrow              7.68225: value(s) in YAML
2024-03-12 20:50:00.378886 INFO pv_opt:     octopus_auto                       = False                                                      False: value in YAML
/homeassistant/appdaemon/apps/pv_opt/pv_opt.py:978: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  pd.to_datetime(values[0], errors="ignore", format="%H:%M")
2024-03-12 20:50:00.380455 INFO pv_opt:     octopus_account                    = A63A07001                                                 A63A07001: YAML default value. No default defined.
/homeassistant/appdaemon/apps/pv_opt/pv_opt.py:978: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  pd.to_datetime(values[0], errors="ignore", format="%H:%M")
2024-03-12 20:50:00.382454 INFO pv_opt:     octopus_api_key                    = ********************************                          ********************************: YAML default value. No default defined.
/homeassistant/appdaemon/apps/pv_opt/pv_opt.py:978: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  pd.to_datetime(values[0], errors="ignore", format="%H:%M")
2024-03-12 20:50:00.384317 INFO pv_opt:     octopus_import_tariff_code         = E-1R-AGILE-FLEX-22-11-25-N                                E-1R-AGILE-FLEX-22-11-25-N: YAML default value. No default defined.
/homeassistant/appdaemon/apps/pv_opt/pv_opt.py:978: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  pd.to_datetime(values[0], errors="ignore", format="%H:%M")
2024-03-12 20:50:00.385999 INFO pv_opt:     octopus_export_tariff_code         = E-1R-OUTGOING-FIX-12M-19-05-13-N                          E-1R-OUTGOING-FIX-12M-19-05-13-N: YAML default value. No default defined.
/homeassistant/appdaemon/apps/pv_opt/pv_opt.py:978: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  pd.to_datetime(values[0], errors="ignore", format="%H:%M")
2024-03-12 20:50:00.393645 WARNING pv_opt: ------------------------------------------------------------
2024-03-12 20:50:00.393791 WARNING pv_opt: Unexpected error running initialize() for pv_opt
2024-03-12 20:50:00.393875 WARNING pv_opt: ------------------------------------------------------------
2024-03-12 20:50:00.394937 WARNING pv_opt: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 335, in initialize
    self._load_args()
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 998, in _load_args
    f"    {item:34s} = {str(self.config[item]):57s} {str(self.get_config(item)):>6s}: value in YAML"
                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 538, in get_config
    x = self.get_ha_value(self.config[item])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 853, in get_ha_value
    raise ValueError(e)
ValueError: HA returned unknown for state of sensor.solis_battery_voltage

2024-03-12 20:50:00.395034 WARNING pv_opt: ------------------------------------------------------------
2024-03-12 20:50:01.130962 INFO pv_opt:   - Got 7 days history from sensor.solis_house_load_today from 05-Mar 20:30 to 12-Mar 20:30
2024-03-12 20:50:01.131659 INFO pv_opt:   - 7 days was expected. OK
/homeassistant/appdaemon/apps/pv_opt/pv_opt.py:1333: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  time_value = pd.to_datetime(state, errors="ignore", format="%H:%M")
2024-03-12 20:50:01.135262 INFO pv_opt:   - Estimated consumption from sensor.solis_house_load_today loaded OK 
2024-03-12 20:50:01.136067 INFO pv_opt: 
2024-03-12 20:50:01.143184 WARNING pv_opt: ------------------------------------------------------------
2024-03-12 20:50:01.143318 WARNING pv_opt: Unexpected error in worker for App pv_opt:
2024-03-12 20:50:01.143413 WARNING pv_opt: Worker Ags: {'id': '0891b3d6476f4646a53b77acf193ff0b', 'name': 'pv_opt', 'objectid': '4ad27b3e54e1483b8ae3565b8cd413f6', 'type': 'scheduler', 'function': <bound method PVOpt.optimise_time of <pv_opt.PVOpt object at 0x7fb90db867d0>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 600, '__thread_id': 'thread-0'}}
2024-03-12 20:50:01.143492 WARNING pv_opt: ------------------------------------------------------------
2024-03-12 20:50:01.144226 WARNING pv_opt: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 1350, in optimise_time
    self.optimise()
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 1413, in optimise
    self.soc_now = self.get_config("id_battery_soc")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 538, in get_config
    x = self.get_ha_value(self.config[item])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 853, in get_ha_value
    raise ValueError(e)
ValueError: HA returned unknown for state of sensor.solis_battery_soc

2024-03-12 20:50:01.144581 WARNING pv_opt: ------------------------------------------------------------

**Comment by fboundy** [comment]
@mergwyn's `config.yaml` should be the right way to go. However, I think the problem is dues to this error which is crashing the load_args method. I'm updating the code to handle this more nicely but you might want to check it's set correctly:

    ValueError: HA returned unknown for state of sensor.solis_battery_voltage

**Comment by lazy-pete** [comment]
Ah - thanks.

I suspect what’s happening is that the Solax integration is interrupted
briefly due to using both Solax and the Solis cloud through a 485 hub
simultaneously (I had to put the SolisCloud dongle back on to troubleshoot
a battery issue). I’ve detached it again and things seem more stable.

IIRC there is another method that allows two masters that doesn’t have this
issue - I just can’t remember what it is !

I just need the solis cloud intermittently for firmware updates etc - I
find their support service really good.

Cheers,

Pete

**Comment by lazy-pete** [comment]
Still seeing this oddity - I’m using the yaml to set defaults, and have overwrite as TRUE, however I still see a dashboard with disparity between the yaml and HA. 

![IMG_6191](https://github.com/fboundy/pv_opt/assets/30950467/38fa03fe-e167-4729-8ccd-1eee006a0d1d)
![IMG_6190](https://github.com/fboundy/pv_opt/assets/30950467/6f1c69fe-0c07-454b-b342-e995d77c8d0b)

[main.log](https://github.com/fboundy/pv_opt/files/14822266/main.log)
[error.log](https://github.com/fboundy/pv_opt/files/14822267/error.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14822268/pv_opt.log)

**Comment by fboundy** [comment]
OK - on my `to do` list

**Comment by lazy-pete** [comment]
I tried editing and resaving the yaml just in case there was a glitch there somehow. Last HA restart seemed to load correctly (restarting at least daily at present as the Solax integration is still dropping out).

**Comment by fboundy** [comment]
Which version of Solax are you on? It's been stable for me for the last week

**Comment by lazy-pete** [comment]
Hi - sorry - I missed your reply. 

Been on various versions of the Solax Integration - currently 2024.04.4b1 

This is still dropping the Modbus connection a few times a day, although the errors seem to point to a loss of modbus connection to the inverter ip address. I don't really understand what's going on there as if it were an issue with my wifi to Elfin EW11 I wouldn't expect a HA restart to resolve it. I've created an automation that triggers a restart if the coinverter RTC doesn't update fot 15mins. Most of the time that is successful, though occasionally the Solax interface doesn't seem to update and I have to manually reload it - the automation already includes code to wait for the solis parameters to populate, so I'm not sure why that happens. It's perhaps unrelated and I need a separate automation to reload the Solax integration periodically.

I've spent some of today putting in the various files for your own Modbus integration, however I cannot see how to actually use it - there is no sign of an innate Modbus integration within my HA instance. Nothing on ~ pip show pymodbus , which is wierd as PV-Opt works fine when the Solax connection is up. 

In terms of my original bug I think it's not an issue - I think I was not waiting long enough after a restart to allow it to setup properly, which it doesn't do until it can pull all the solax entities. Can close this ticket I think - apologies again for the delay. I'll search for other Modbus related issues and see if I can get to the bottom of that.

Cheers,

Pete

**Comment by fboundy** [comment]
ModBus is part of core HA so with mine you just need the YAML file and a HA restart no need to install pymodbus or any integration

**Comment by lazy-pete** [comment]
Thanks - does that then create the various entities I would need to remap
for a second dashboard (would probably disable Solax but leave the
dashboard initially).

That all seemed to be missing when I gave it a try …

Cheers,

Pete

**Comment by fboundy** [comment]
Yes, should do.

I have both running in parallel - just use a different name than ‘Solis’ for one of them

**Comment by lazy-pete** [comment]
Thanks - I’ll try that out. 

Meantime I seem to have lost a couple of dashboard templates, but I can’t work out why. Both the templates yaml and the main HA config yaml seem to have them in correctly (I did have to tweak a few copy / paste indent issues to get the green tick) but the dashboard doesn’t seem to be picking them up. Have I done anything obvious incorrectly ?

cheers,

pete

![IMG_6360](https://github.com/fboundy/pv_opt/assets/30950467/9b7aebd0-ea24-45d0-9cff-a3035a7aeb3d)
![IMG_6359](https://github.com/fboundy/pv_opt/assets/30950467/6106899f-1f59-4ce4-86b5-20f2a741b663)
![IMG_6362](https://github.com/fboundy/pv_opt/assets/30950467/5700ce0e-d93a-4f14-b18c-fe025368ce6f)
![IMG_6361](https://github.com/fboundy/pv_opt/assets/30950467/5c2aacce-4c94-4c94-97c2-976982551d38)

**Comment by lazy-pete** [comment]
> Yes, should do. I have both running in parallel - just use a different name than ‘Solis’ for one of them
> […](#)


Forgive my ignorance, but do you mean you’ve installed the Appdaemon app twice and referenced different yaml files ? I thought I perhaps just uncommented both inverter models, however that creates issues.

**Comment by fboundy** [comment]
The core HA integration doesn’t use AppDaemon. It is part of HA’s configuration.yaml file.

**Comment by lazy-pete** [comment]
So if I just pop all the yaml files etc in the correct places / with
correct links / ip etc and create a new dashboard it will ‘just work’ ?

Still struggling to get the import / export bits available as well. The
base entity data is there - it’s just the templates that aren’t reporting.

Cheers,

Pete

**Comment by fboundy** [comment]
Yes should be that simple

**Comment by lazy-pete** [comment]
Hi - really sorry, but still struggling to get my head around your Modbus integration. 

The templates etc seem to work in that I have a bunch of Modbus entities that seem relevant. A bit unclear whether I also need to set up all the dashboard details etc for your own Modbus , and how that interacts with just selecting that inverter in PV-opt and it’s own dashboard thereafter. 

What I can’t get my head around is using both in parallel with PV-opt - that requires commenting the inverter used in the config.yaml , and to run those in parallel I can’t activate two ‘inverters’ with different setups. When you say you run both Solax and native Modbus ‘in parallel’ do you mean on the same HA instance, or are you running two separate installs ? 

I’ve also tried completely removing and reinstalling Solax Modbus, and now have an interesting collection of entities with _2 etc 

Sorry if I’m being really dim !

**Comment by fboundy** [comment]
They will both work in parallel in HA but you can’t use both in parallel in pv_opt. You either select SOLIS_SOLAX_MODBUS or SOLIS_CORE_MODBUS as the inverter type and set the parameters accordingly.

**Comment by lazy-pete** [comment]
That makes more sense - will ‘complete’ the Modbus version install and then
try both alternately with PV-opt.

Ps - I had to add a ‘state’ to the first template sensor in Modbus to get
it all working - was throwing a HA error and I only got the rest of the
templates available after doing that - maybe something changed. Will put a
ticket on the Modbus GitHub.

Cheers,

Pete
