### ISSUE TITLE
This is not working for me any more.  Doesn't charge on a daily basis.

### ISSUE THREAD

**Issue by philicibine** [stevebuk1/pv_opt#311]
This is happening on a daily basis now.  We have had some cloudy days and it has not been charging the battery.  Could really do with some help.  The pv_opt log below seems to run right after a reboot for a few times and then just stops.  See below.

```
22:39:37     INFO: Starting Opimisation with discharge enabled
22:39:37     INFO: -------------------------------------------
22:39:37     INFO:
22:39:37     INFO: Checking tariffs:
22:39:37     INFO: -----------------
22:39:37     INFO:
22:39:37     INFO:   Contract last loaded at 01-Dec 19:50 UTC
22:39:37     INFO:
22:39:37     INFO: Checking tariff prices vs Octopus Energy Integration:
22:39:37     INFO: -----------------------------------------------------
22:39:37     INFO:
22:39:37     INFO:   Import: Average Prices - PV_OPT: 21.44 p/kWh  OE Integration: 21.44 p/kWh  Mean difference:  0.00 p/kWh
22:39:37     INFO:   Export: Average Prices - PV_OPT: 15.00 p/kWh  OE Integration: 15.00 p/kWh  Mean difference:  0.00 p/kWh
22:39:37     INFO:
22:39:37     INFO: Checking tariff start and end times:
22:39:37     INFO: ------------------------------------
22:39:37     INFO:   Import: E-1R-AGILE-23-12-06-A                    Start: 2024-11-22 13:00:00+0000 End: 2024-12-02 23:00:00+0000
22:39:37     INFO:   Export: E-1R-OUTGOING-FIX-12M-19-05-13-A         Start: 2019-05-15 23:00:00+0000 End: N/A
22:39:37     INFO:   AGILE tariff detected. Rates will update at 16:00 daily
22:39:37     INFO:   Tariffs OK
22:39:37     INFO:
22:39:37     INFO: Solcast forecast loaded OK
22:39:37     INFO:
22:39:37     INFO: Getting expected consumption data for 2024-12-01 00:00:00+0000 to 2024-12-03 00:00:00+0000:
22:39:37     INFO: Getting consumpion
22:39:38     INFO:   - Got 10 days history from sensor.solax_house_load_today from 21-Nov 23:00 UTC to 01-Dec 22:30 UTC
22:39:38     INFO:   - 10 days was expected. OK
22:39:39     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
22:39:39     INFO:   - Total consumption: 47.2 kWh
22:39:39     INFO:
22:39:39     INFO: Initial SOC: 20.0
22:39:39     INFO: Calculating Base flows:
22:39:39     INFO:
22:39:39     INFO: Optimising for Solcast 50% confidence level forecast from 01-Dec 22:30 UTC to 02-Dec 23:30 UTC
22:40:05     INFO: Optimiser prices loaded for period 01/12 22:30 UTC - 02/12 23:30 UTC
22:40:05     INFO: Base cost:  564.7
22:40:05     INFO:
22:40:05     INFO: High Cost Usage Swaps
22:40:05     INFO: ---------------------
22:40:05     INFO:
22:40:06     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 02:30 GMT:  7.46p/kWh  9.88p  SOC:  20.0%-> 20.0% New SOC:  20.0%-> 32.2% Net:  560.0
22:40:06     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 02:30 GMT:  7.46p/kWh  9.88p  SOC:  20.0%-> 32.2% New SOC:  20.0%-> 44.4% Net:  544.0
22:40:06     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 02:30 GMT:  7.46p/kWh  9.88p  SOC:  20.0%-> 44.4% New SOC:  20.0%-> 47.6% Net:  538.4
22:40:06     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 03:30 GMT:  7.83p/kWh 10.38p  SOC:  45.5%-> 43.3% New SOC:  45.5%-> 57.7% Net:  520.8
22:40:06     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 03:30 GMT:  7.83p/kWh 10.38p  SOC:  45.5%-> 57.7% New SOC:  45.5%-> 69.9% Net:  503.3
22:40:07     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 03:30 GMT:  7.83p/kWh 10.38p  SOC:  45.5%-> 69.9% New SOC:  45.5%-> 73.1% Net:  499.1
22:40:07     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 01:30 GMT:  8.86p/kWh 11.75p  SOC:  20.0%-> 20.0% New SOC:  20.0%-> 32.2% Net:  486.9
22:40:07     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 01:30 GMT:  8.86p/kWh 11.75p  SOC:  20.0%-> 32.2% New SOC:  20.0%-> 44.4% Net:  472.0
22:40:07     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 01:30 GMT:  8.86p/kWh 11.75p  SOC:  20.0%-> 44.4% New SOC:  20.0%-> 47.6% Net:  466.7
22:40:08     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 04:30 GMT: 12.13p/kWh 16.07p  SOC:  95.5%-> 92.9% New SOC:  95.5%->100.0% Net:  452.7
22:40:08     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 06:30 GMT: 20.39p/kWh 27.03p  SOC:  91.9%-> 89.2% New SOC:  91.9%->100.0% Net:  431.7
22:40:08     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 11:00 GMT: 20.70p/kWh 27.43p  SOC:  84.8%-> 80.8% New SOC:  84.8%-> 90.9% Net:  402.7
22:40:08     INFO: 02/12 18:30 GMT:  1.33 kWh at  42.51p. <==> 02/12 11:00 GMT: 20.70p/kWh 27.43p  SOC:  84.8%-> 97.0% New SOC:  84.8%-> 95.0% Net:  397.6
22:40:09     INFO: 02/12 18:30 GMT:  1.31 kWh at  42.20p. <==> 02/12 15:00 GMT: 22.17p/kWh 29.13p  SOC:  65.1%-> 60.7% New SOC:  65.1%-> 77.2% Net:  383.3
22:40:10     INFO: 02/12 19:00 GMT:  0.37 kWh at   8.35p. <==> 02/12 15:00 GMT: 22.17p/kWh  8.29p  SOC:  65.1%-> 77.2% New SOC:  65.1%-> 80.6% Net:  383.3
22:40:10     INFO: 01/12 23:00 GMT:  0.37 kWh at   6.30p. <==> 01/12 22:30 GMT: 16.61p/kWh  6.21p  SOC:  20.0%-> 20.0% New SOC:  20.0%-> 23.4% Net:  383.2
22:40:10     INFO: 02/12 01:00 GMT:  0.31 kWh at   3.65p. <==> 02/12 00:00 GMT: 11.03p/kWh  3.37p  SOC:  20.0%-> 20.0% New SOC:  20.0%-> 22.8% Net:  382.5
22:40:11     INFO: 02/12 01:00 GMT:  0.24 kWh at   2.94p. <==> 02/12 00:00 GMT: 11.03p/kWh  2.62p  SOC:  20.0%-> 22.8% New SOC:  20.0%-> 25.0% Net:  382.2
22:40:18     INFO:
22:40:18     INFO: Low Cost Charging
22:40:18     INFO: ------------------
22:40:18     INFO:
22:40:18     INFO: Max export price when there is no forced charge: 15.00p/kWh.
22:40:18     INFO: 8 slots have an import price less than the max export price
22:40:19     INFO:
22:40:19     INFO: Charge net cost delta: -0.0p: < Pass Threshold 4.0p => Slots Excluded
22:40:19     INFO:
22:40:19     INFO: Forced Discharging
22:40:19     INFO: ------------------
22:40:19     INFO:
22:40:19     INFO: 41 slots have an export price greater than the min import price
22:40:26     INFO:
22:40:26     INFO: Discharge net cost delta: -0.0p: < Discharge threshold (5.0p) => Slots excluded
22:40:26     INFO: Iteration  1: Slots added:   0
22:40:26     INFO:
22:40:26     INFO: Removing cyclic charge/discharge
22:40:26     INFO:   Net cost revised from 382.2p to 382.2p
22:40:26     INFO:
22:40:26     INFO: Optimisation Summary
22:40:26     INFO: --------------------
22:40:26     INFO:
22:40:26     INFO:   Base cost:                                564.7p
22:40:27     INFO:   Optimised cost (Optimised Charging):      382.2p
22:40:27     INFO:   Optimised cost (Optimised PV Export):     382.2p
22:40:27     INFO:   Optimised cost (Forced Discharge):        382.2p <=== Current Setup
22:40:27     INFO:
22:40:27     INFO: Checking for Hold SOC slots
22:40:27     INFO:
22:40:27     INFO: Optimal forced charge/discharge slots:
22:40:27     INFO:   01-Dec 22:30 GMT - 01-Dec 23:00 GMT  Power:   700W  SOC:   20% ->   23%
22:40:27     INFO:   02-Dec 00:00 GMT - 02-Dec 00:30 GMT  Power:  1100W  SOC:   20% ->   25%
22:40:27     INFO:   02-Dec 01:30 GMT - 02-Dec 02:00 GMT  Power:  6000W  SOC:   20% ->   48%
22:40:27     INFO:   02-Dec 02:30 GMT - 02-Dec 03:00 GMT  Power:  6000W  SOC:   45% ->   73%
22:40:27     INFO:   02-Dec 03:30 GMT - 02-Dec 04:00 GMT  Power:  6000W  SOC:   71% ->   98%
22:40:27     INFO:   02-Dec 04:30 GMT - 02-Dec 05:00 GMT  Power:  1400W  SOC:   96% ->  100%
22:40:27     INFO:   02-Dec 06:30 GMT - 02-Dec 07:00 GMT  Power:  2100W  SOC:   92% ->  100%
22:40:27     INFO:   02-Dec 11:00 GMT - 02-Dec 12:00 GMT  Power:  2200W  SOC:   85% ->  100%
22:40:27     INFO:   02-Dec 15:00 GMT - 02-Dec 15:30 GMT  Power:  3400W  SOC:   65% ->   81%
22:40:27     INFO:
22:40:27     INFO: Plan time: 01-Dec 22:30 - 02-Dec 23:30 Initial SOC: 20.0 Base Cost: 564.7 Opt Cost: 382.2
22:40:27     INFO:
22:40:27     INFO: Optimiser elapsed time 49.6 seconds
22:40:27     INFO:
22:40:27     INFO:
22:40:27     INFO: Output written to sensor.pvopt_optimiser_elapsed
22:40:27     INFO: Average unit cost today: 23.50p/kWh
22:40:27     INFO: Output written to sensor.pvopt_unit_cost_today
22:40:28     INFO: Output written to sensor.pvopt_base_cost
22:40:28     INFO: Output written to sensor.pvopt_opt_cost
22:40:28     INFO: Output written to sensor.pvopt_charge_start
22:40:28     INFO: Output written to sensor.pvopt_charge_end
22:40:28     INFO: Output written to sensor.pvopt_charge_current
22:40:28     INFO: Output written to sensor.pvopt_soc_h1
22:40:28     INFO: Output written to sensor.pvopt_soc_h4
22:40:28     INFO: Output written to sensor.pvopt_soc_h8
22:40:28     INFO: Output written to sensor.pvopt_soc_h12
22:40:28     INFO:
22:40:28     INFO: Current inverter status:
22:40:28     INFO: ------------------------
22:40:28     INFO:   mode              : Self-Use
22:40:28     INFO:   code              : 35
22:40:28     INFO:   switches          :
22:40:28     INFO:     SelfUse         : True
22:40:28     INFO:     Timed           : True
22:40:28     INFO:     OffGrid         : False
22:40:28     INFO:     BatteryWake     : False
22:40:28     INFO:     Backup          : False
22:40:28     INFO:     GridCharge      : True
22:40:28     INFO:     FeedInPriority  : False
22:40:28     INFO:   charge            :
22:40:29     INFO:     start           : 01-Dec 19:53 GMT
22:40:29     INFO:     end             : 01-Dec 19:53 GMT
22:40:29     INFO:     active          : False
22:40:29     INFO:   discharge         :
22:40:29     INFO:     start           : 01-Dec 00:00 GMT
22:40:29     INFO:     end             : 01-Dec 00:00 GMT
22:40:29     INFO:     current         : 0.0
22:40:29     INFO:     active          : False
22:40:29     INFO:   hold_soc          :
22:40:29     INFO:     active          : False
22:40:29     INFO:     soc             : 80.0
22:40:29     INFO:
22:40:29     INFO: Current charge/discharge window ends in 19.5 minutes.
22:40:29     INFO: Updating inverter charge control:
22:40:29     INFO:   start: 2024-12-01 22:40:29.066892+00:00
22:40:29     INFO:   end: 2024-12-01 23:00:00+00:00
22:40:29     INFO:   power: 700
22:40:29     INFO:   target_soc: 23
22:40:29     INFO: Entity: number.solax_timed_charge_start_hours Value: 22.0  Old State: 19.0 New state: 22.0 Diff:  3.0 Tol:  0.0
22:40:29     INFO: Wrote charge start hours of 22 to inverter
22:40:30     INFO: Entity: number.solax_timed_charge_start_minutes Value: 40.0  Old State: 53.0 New state: 40.0 Diff: 13.0 Tol:  0.0
22:40:30     INFO: Wrote charge start minutes of 40 to inverter
22:40:30     INFO: Entity: number.solax_timed_charge_end_hours Value: 23.0  Old State: 19.0 New state: 23.0 Diff:  4.0 Tol:  0.0
22:40:30     INFO: Wrote charge end hours of 23 to inverter
22:40:31     INFO: Entity: number.solax_timed_charge_end_minutes Value:  0.0  Old State: 53.0 New state:  0.0 Diff: 53.0 Tol:  0.0
22:40:31     INFO: Wrote charge end minutes of 0 to inverter
22:40:31     INFO: Successfully pressed button button.solax_update_charge_discharge_times
22:40:31     INFO: Power 700 = 13.4A at 52.4V
22:40:32     INFO: Current 13.4A written to inverter
22:40:32     INFO: Waiting for inverter Read cycle: 72 seconds
22:58:00     INFO:
22:58:00     INFO: Comparing yesterday's tariffs
22:58:00     INFO: -----------------------------
22:58:00     INFO:
22:58:00     INFO: Getting yesterday's solar generation (30-Nov 00:00 UTC - 01-Dec 00:00 UTC):
22:58:00     INFO:
22:58:00     INFO: Getting expected consumption data for 2024-11-30 00:00:00+0000 to 2024-12-01 00:00:00+0000:
22:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
22:58:00     INFO: Getting consumpion
22:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 29-Nov 23:00 UTC to 01-Dec 22:30 UTC
22:58:00     INFO:   - 2 days was expected. OK
22:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
22:58:00     INFO:   - Total consumption: 19.3 kWh
22:58:00     INFO:
22:58:00     INFO: Start:       30-Nov 00:00 UTC
22:58:00     INFO: End:         01-Dec 00:00 UTC
22:58:00     INFO: Initial SOC:            22.0%
22:58:00     INFO: Consumption:            19.3 kWh
22:58:00     INFO: Solar:                   1.0 kWh
22:58:05     INFO:
22:58:05     INFO: Net Cost comparison:
22:58:05     INFO:
22:58:05     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
22:58:05     INFO:   ------                     ---------------  --------------------
22:58:06     INFO:   Actual                                                     4.718
22:58:28     INFO:   current                              4.765                 3.974
22:58:52     INFO:   Agile_Fix                            4.765                 3.974
22:59:32     INFO:   Eco7_Fix                             5.551                 4.276
22:59:51     INFO:   Flux                                 5.281                 4.310
23:58:00     INFO:
23:58:00     INFO: Comparing yesterday's tariffs
23:58:00     INFO: -----------------------------
23:58:00     INFO:
23:58:00     INFO: Getting yesterday's solar generation (30-Nov 00:00 UTC - 01-Dec 00:00 UTC):
23:58:00     INFO:
23:58:00     INFO: Getting expected consumption data for 2024-11-30 00:00:00+0000 to 2024-12-01 00:00:00+0000:
23:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
23:58:00     INFO: Getting consumpion
23:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 30-Nov 00:00 UTC to 01-Dec 23:30 UTC
23:58:00     INFO:   - 2 days was expected. OK
23:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
23:58:00     INFO:   - Total consumption: 19.3 kWh
23:58:00     INFO:
23:58:00     INFO: Start:       30-Nov 00:00 UTC
23:58:00     INFO: End:         01-Dec 00:00 UTC
23:58:00     INFO: Initial SOC:            22.0%
23:58:00     INFO: Consumption:            19.3 kWh
23:58:00     INFO: Solar:                   1.0 kWh
23:58:05     INFO:
23:58:05     INFO: Net Cost comparison:
23:58:05     INFO:
23:58:05     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
23:58:05     INFO:   ------                     ---------------  --------------------
23:58:05     INFO:   Actual                                                     4.718
23:58:28     INFO:   current                              4.765                 3.974
23:58:51     INFO:   Agile_Fix                            4.765                 3.974
23:59:35     INFO:   Eco7_Fix                             5.551                 4.276
23:59:54     INFO:   Flux                                 5.281                 4.310
00:58:00     INFO:
00:58:00     INFO: Comparing yesterday's tariffs
00:58:00     INFO: -----------------------------
00:58:00     INFO:
00:58:00     INFO: Getting yesterday's solar generation (01-Dec 00:00 UTC - 02-Dec 00:00 UTC):
00:58:00     INFO:
00:58:00     INFO: Getting expected consumption data for 2024-12-01 00:00:00+0000 to 2024-12-02 00:00:00+0000:
00:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
00:58:00     INFO: Getting consumpion
00:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 30-Nov 01:00 UTC to 02-Dec 00:30 UTC
00:58:00     INFO:   - 2 days was expected. OK
00:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
00:58:00     INFO:   - Total consumption: 22.8 kWh
00:58:01     INFO:
00:58:01     INFO: Start:       01-Dec 00:00 UTC
00:58:01     INFO: End:         02-Dec 00:00 UTC
00:58:01     INFO: Initial SOC:            19.5%
00:58:01     INFO: Consumption:            22.8 kWh
00:58:01     INFO: Solar:                   0.7 kWh
00:58:18     INFO:
00:58:18     INFO: Net Cost comparison:
00:58:18     INFO:
00:58:18     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
00:58:18     INFO:   ------                     ---------------  --------------------
00:58:18     INFO:   Actual                                                     5.314
00:59:00     INFO:   current                              5.921                 4.097
00:59:41     INFO:   Agile_Fix                            5.921                 4.097
01:00:21     INFO:   Eco7_Fix                             6.934                 5.696
01:00:38     INFO:   Flux                                 6.499                 5.352
01:58:00     INFO:
01:58:00     INFO: Comparing yesterday's tariffs
01:58:00     INFO: -----------------------------
01:58:00     INFO:
01:58:00     INFO: Getting yesterday's solar generation (01-Dec 00:00 UTC - 02-Dec 00:00 UTC):
01:58:00     INFO:
01:58:00     INFO: Getting expected consumption data for 2024-12-01 00:00:00+0000 to 2024-12-02 00:00:00+0000:
01:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
01:58:00     INFO: Getting consumpion
01:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 30-Nov 02:00 UTC to 02-Dec 01:30 UTC
01:58:00     INFO:   - 2 days was expected. OK
01:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
01:58:00     INFO:   - Total consumption: 22.8 kWh
01:58:00     INFO:
01:58:00     INFO: Start:       01-Dec 00:00 UTC
01:58:00     INFO: End:         02-Dec 00:00 UTC
01:58:00     INFO: Initial SOC:            19.5%
01:58:00     INFO: Consumption:            22.8 kWh
01:58:00     INFO: Solar:                   0.7 kWh
01:58:03     INFO:
01:58:03     INFO: Net Cost comparison:
01:58:03     INFO:
01:58:03     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
01:58:03     INFO:   ------                     ---------------  --------------------
01:58:03     INFO:   Actual                                                     5.314
01:58:45     INFO:   current                              5.921                 4.097
01:59:26     INFO:   Agile_Fix                            5.921                 4.097
02:00:07     INFO:   Eco7_Fix                             6.934                 5.696
02:00:17     INFO:   Flux                                 6.499                 5.351
02:58:00     INFO:
02:58:00     INFO: Comparing yesterday's tariffs
02:58:00     INFO: -----------------------------
02:58:00     INFO:
02:58:00     INFO: Getting yesterday's solar generation (01-Dec 00:00 UTC - 02-Dec 00:00 UTC):
02:58:00     INFO:
02:58:00     INFO: Getting expected consumption data for 2024-12-01 00:00:00+0000 to 2024-12-02 00:00:00+0000:
02:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
02:58:00     INFO: Getting consumpion
02:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 30-Nov 03:00 UTC to 02-Dec 02:30 UTC
02:58:00     INFO:   - 2 days was expected. OK
02:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
02:58:00     INFO:   - Total consumption: 22.8 kWh
02:58:00     INFO:
02:58:00     INFO: Start:       01-Dec 00:00 UTC
02:58:00     INFO: End:         02-Dec 00:00 UTC
02:58:00     INFO: Initial SOC:            19.5%
02:58:00     INFO: Consumption:            22.8 kWh
02:58:00     INFO: Solar:                   0.7 kWh
02:58:03     INFO:
02:58:03     INFO: Net Cost comparison:
02:58:03     INFO:
02:58:03     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
02:58:03     INFO:   ------                     ---------------  --------------------
02:58:03     INFO:   Actual                                                     5.314
02:58:45     INFO:   current                              5.921                 4.097
02:59:26     INFO:   Agile_Fix                            5.921                 4.097
03:00:06     INFO:   Eco7_Fix                             6.934                 5.696
03:00:23     INFO:   Flux                                 6.499                 5.351
03:58:00     INFO:
03:58:00     INFO: Comparing yesterday's tariffs
03:58:00     INFO: -----------------------------
03:58:00     INFO:
03:58:00     INFO: Getting yesterday's solar generation (01-Dec 00:00 UTC - 02-Dec 00:00 UTC):
03:58:00     INFO:
03:58:00     INFO: Getting expected consumption data for 2024-12-01 00:00:00+0000 to 2024-12-02 00:00:00+0000:
03:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
03:58:00     INFO: Getting consumpion
03:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 30-Nov 04:00 UTC to 02-Dec 03:30 UTC
03:58:00     INFO:   - 2 days was expected. OK
03:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
03:58:00     INFO:   - Total consumption: 22.8 kWh
03:58:00     INFO:
03:58:00     INFO: Start:       01-Dec 00:00 UTC
03:58:00     INFO: End:         02-Dec 00:00 UTC
03:58:00     INFO: Initial SOC:            19.5%
03:58:00     INFO: Consumption:            22.8 kWh
03:58:00     INFO: Solar:                   0.7 kWh
03:58:03     INFO:
03:58:03     INFO: Net Cost comparison:
03:58:03     INFO:
03:58:03     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
03:58:03     INFO:   ------                     ---------------  --------------------
03:58:03     INFO:   Actual                                                     5.314
03:58:44     INFO:   current                              5.921                 4.097
03:59:26     INFO:   Agile_Fix                            5.921                 4.097
04:00:06     INFO:   Eco7_Fix                             6.934                 5.696
04:00:23     INFO:   Flux                                 6.499                 5.352
04:58:00     INFO:
04:58:00     INFO: Comparing yesterday's tariffs
04:58:00     INFO: -----------------------------
04:58:00     INFO:
04:58:00     INFO: Getting yesterday's solar generation (01-Dec 00:00 UTC - 02-Dec 00:00 UTC):
04:58:00     INFO:
04:58:00     INFO: Getting expected consumption data for 2024-12-01 00:00:00+0000 to 2024-12-02 00:00:00+0000:
04:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
04:58:00     INFO: Getting consumpion
04:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 30-Nov 05:00 UTC to 02-Dec 04:30 UTC
04:58:00     INFO:   - 2 days was expected. OK
04:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
04:58:00     INFO:   - Total consumption: 22.8 kWh
04:58:00     INFO:
04:58:00     INFO: Start:       01-Dec 00:00 UTC
04:58:00     INFO: End:         02-Dec 00:00 UTC
04:58:00     INFO: Initial SOC:            19.5%
04:58:00     INFO: Consumption:            22.8 kWh
04:58:00     INFO: Solar:                   0.7 kWh
04:58:03     INFO:
04:58:03     INFO: Net Cost comparison:
04:58:03     INFO:
04:58:03     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
04:58:03     INFO:   ------                     ---------------  --------------------
04:58:03     INFO:   Actual                                                     5.314
04:58:44     INFO:   current                              5.921                 4.097
04:59:26     INFO:   Agile_Fix                            5.921                 4.097
05:00:06     INFO:   Eco7_Fix                             6.934                 5.696
05:00:22     INFO:   Flux                                 6.499                 5.352
05:58:00     INFO:
05:58:00     INFO: Comparing yesterday's tariffs
05:58:00     INFO: -----------------------------
05:58:00     INFO:
05:58:00     INFO: Getting yesterday's solar generation (01-Dec 00:00 UTC - 02-Dec 00:00 UTC):
05:58:00     INFO:
05:58:00     INFO: Getting expected consumption data for 2024-12-01 00:00:00+0000 to 2024-12-02 00:00:00+0000:
05:58:00     INFO:   - Start and end are both in past so actuals will be used with no weighting
05:58:00     INFO: Getting consumpion
05:58:00     INFO:   - Got 2 days history from sensor.solax_house_load_today from 30-Nov 06:00 UTC to 02-Dec 05:30 UTC
05:58:00     INFO:   - 2 days was expected. OK
05:58:00     INFO:   - Estimated consumption from sensor.solax_house_load_today loaded OK
05:58:00     INFO:   - Total consumption: 22.8 kWh
05:58:00     INFO:
05:58:00     INFO: Start:       01-Dec 00:00 UTC
05:58:00     INFO: End:         02-Dec 00:00 UTC
05:58:00     INFO: Initial SOC:            19.5%
05:58:00     INFO: Consumption:            22.8 kWh
05:58:00     INFO: Solar:                   0.7 kWh
05:58:03     INFO:
05:58:03     INFO: Net Cost comparison:
05:58:03     INFO:
05:58:03     INFO:   Tariff                     Base Cost (GBP)  Optimised Cost (GBP)
05:58:03     INFO:   ------                     ---------------  --------------------
05:58:03     INFO:   Actual                                                     5.314
05:58:44     INFO:   current                              5.921                 4.097
05:59:26     INFO:   Agile_Fix                            5.921                 4.097
06:00:06     INFO:   Eco7_Fix                             6.934                 5.696
06:00:23     INFO:   Flux                                 6.499                 5.352
```
This is the error log.

```
19:38:43 WARNING pv_opt: ------------------------------------------------------------
19:54:31 WARNING pv_opt: ------------------------------------------------------------
19:54:31 WARNING pv_opt: Unexpected error running initialize() for pv_opt
19:54:31 WARNING pv_opt: ------------------------------------------------------------
19:54:31 WARNING pv_opt: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 558, in initialize
    self.optimise()
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 1892, in optimise
    status = self.inverter.status
             ^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 548, in status
    status = self._solis_state()
             ^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 793, in _solis_state
    and status[direction]["current"] > 0
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'current'

19:54:31 WARNING pv_opt: ------------------------------------------------------------
22:41:45 WARNING pv_opt: ------------------------------------------------------------
22:41:45 WARNING pv_opt: Unexpected error in worker for App pv_opt:
22:41:45 WARNING pv_opt: Worker Ags: {'id': '58a8e556778b4bb58ec1bd6af4c4a492', 'name': 'pv_opt', 'objectid': 'dd33d9aed6564a0dadb1297111e4d200', 'type': 'state', 'function': <bound method PVOpt.optimise_state_change of <pv_opt.PVOpt object at 0x7f8c69a410>>, 'attribute': 'state', 'entity': 'number.pvopt_optimise_frequency_minutes', 'new_state': '10', 'old_state': '30', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
22:41:45 WARNING pv_opt: ------------------------------------------------------------
22:41:45 WARNING pv_opt: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1045, in worker
    funcref(
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 1597, in optimise_state_change
    self.optimise()
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 1892, in optimise
    status = self.inverter.status
             ^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 548, in status
    status = self._solis_state()
             ^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 793, in _solis_state
    and status[direction]["current"] > 0
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'current'

22:41:45 WARNING pv_opt: ------------------------------------------------------------
```
This is after trying a fresh install.  Any idea what is happening?

**Comment by philicibine** [comment]
Trying another fresh install.  Have deleted the mosquitto.db.  Looking at the log above it seems to get stuck and loop at comparing tarrifs.

**Comment by philicibine** [comment]
Seeing alot of this now too

```
07:28:09 CRITICAL AppDaemon: Thread thread-0 has died
07:28:09 CRITICAL AppDaemon: Pinned apps were: ['pv_opt']
07:28:09 CRITICAL AppDaemon: Thread will be restarted
07:28:09 INFO AppDaemon: Adding thread 0
07:28:10 CRITICAL AppDaemon: Thread thread-0 has died
07:28:10 CRITICAL AppDaemon: Pinned apps were: ['pv_opt']
07:28:10 CRITICAL AppDaemon: Thread will be restarted
07:28:10 INFO AppDaemon: Adding thread 0
```
Will try a reboot

**Comment by fboundy** [comment]
Which version number is this?

**Comment by philicibine** [comment]
latest 3.18.2.  Just did a redownload

**Comment by fboundy** [comment]
Ok thanks.

**Comment by fboundy** [comment]
Hopefully fixed with 3.18.3 which I've just released

**Comment by philicibine** [comment]
Thanks!  Will update now and see how it goes!

**Comment by philicibine** [comment]
Good morning.  Just an update to say things seem to be running smoothly.  Thankyou for the fix.
