### ISSUE TITLE
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements

### ISSUE THREAD

**Issue by philicibine** [stevebuk1/pv_opt#316]
Seeing this in the logs today

```
10:00:28 WARNING pv_opt: ------------------------------------------------------------
10:00:28 WARNING pv_opt: Unexpected error in worker for App pv_opt:
10:00:28 WARNING pv_opt: Worker Ags: {'id': 'cb7dde9d13694ac2864fe8a027274f4d', 'name': 'pv_opt', 'objectid': '1b03b0d08f544b20b67db5ffbbfba942', 'type': 'scheduler', 'function': <bound method PVOpt._compare_tariff_cb of <pv_opt.PVOpt object at 0x7f7c55f850>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 3600, '__thread_id': 'thread-0'}}
10:00:28 WARNING pv_opt: ------------------------------------------------------------
10:00:28 WARNING pv_opt: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 1022, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/usr/lib/python3.11/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
    return f(*args, **kw)
           ^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 783, in _compare_tariff_cb
    self._compare_tariffs()
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 2695, in _compare_tariffs
    static = pd.concat([solar, consumption], axis=1).set_axis(["solar", "consumption"], axis=1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pandas/core/frame.py", line 5357, in set_axis
    return super().set_axis(labels, axis=axis, copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pandas/core/generic.py", line 792, in set_axis
    return self._set_axis_nocheck(labels, axis, inplace=False, copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pandas/core/generic.py", line 804, in _set_axis_nocheck
    setattr(obj, obj._get_axis_name(axis), labels)
  File "/usr/lib/python3.11/site-packages/pandas/core/generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/lib/python3.11/site-packages/pandas/core/generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/usr/lib/python3.11/site-packages/pandas/core/internals/base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
```

**Comment by philicibine** [comment]
rebooted and no error for now.
