### ISSUE TITLE
AppDaemon initialization error

### ISSUE THREAD

**Issue by SzosszeNET** [stevebuk1/pv_opt#93]
New setup, not sure how to reproduce - on appdaemon I'm seeing with 3.5.2

2024-01-25 19:52:32.001905 WARNING pv_opt: ------------------------------------------------------------
2024-01-25 19:52:32.002290 WARNING pv_opt: Unexpected error running initialize() for pv_opt
2024-01-25 19:52:32.002418 WARNING pv_opt: ------------------------------------------------------------
2024-01-25 19:52:32.005096 WARNING pv_opt: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 292, in initialize
    self._compare_tariffs()
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 1879, in _compare_tariffs
    consumption = self.load_consumption(start, end)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 1866, in load_consumption
    x = temp.to_numpy() + y.to_numpy()
        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (48,) (13,) 

2024-01-25 19:52:32.006090 WARNING pv_opt: ------------------------------------------------------------
2024-01-25 19:52:32.006778 INFO AppDaemon: App initialization complete

As a result pvopt sensors are missing

<img width="1240" alt="image" src="https://github.com/fboundy/pv_opt/assets/32844005/43c05d99-8e0f-42a4-be7f-c4635531fe1a">


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by SzosszeNET** [comment]
This was indeed because "alt_tariffs" needed commented out, thank you.
